import cv2
import imutils
import logging
import requests
import time
from imutils.video import VideoStream
import logging


# replace this with the url generated by the Wyze app
rtsp_url = "rtsp://davidr:tigger85@192.168.0.142/live"

vs = VideoStream(rtsp_url).start()


starttime = time.time()
INTERVAL = 60.0 #seconds


# Function to call API


while True:
    print("tick")
    time.sleep(INTERVAL - ((time.time() - starttime) % INTERVAL))
